kind: pipeline
name: default

clone:
  depth: 1

env: &env
  CARGO_HOME: ./.cargo

steps:
- name: build
  image: rust:1.66
  pull: true
  environment: *env
  commands:
  - cargo build --tests

- name: test
  image: rust:1.66
  environment: *env
  commands:
  - cargo test
  depends_on:
  - build

- name: lint
  image: rust:1.66
  environment: *env
  commands:
  - rustup component add clippy
  # wait for test step to finish building
  - sleep 2
  - cargo clippy --tests -- -D warnings
  depends_on:
  - build

- name: notify
  image: drillster/drone-email
  settings:
    host: {from_secret: smtp_hostname}
    username: {from_secret: smtp_username}
    password: {from_secret: smtp_password}
    from: Drone CI <drone@grinaker.org>
  when:
    status:
    - changed
    - failure
  depends_on:
  - test
  - lint
