//! The planner builds and optimizes an execution plan based on a SQL
//! statement's Abstract Syntax Tree (AST) generated by the parser.

mod optimizer;
mod plan;
mod planner;

pub use plan::{Aggregate, Direction, Node, Plan};
pub use planner::{Planner, Scope};

#[cfg(test)]
pub use optimizer::OPTIMIZERS;
